# Generated by Django 5.1.6 on 2025-12-24 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userdetail_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersnew',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
