# Generated by Django 5.1.6 on 2025-12-30 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userdetail_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountInfo',
            fields=[
                ('txn_id', models.AutoField(primary_key=True, serialize=False)),
                ('account_no', models.PositiveIntegerField(editable=False, unique=True)),
                ('current_bal', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('txn_type', models.CharField(blank=True, max_length=10, null=True)),
                ('txn_datetime', models.DateTimeField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
            ],
            options={
                'db_table': 'account_info',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='usersnew',
            options={'managed': False},
        ),
    ]
