# Generated by Django 5.1.6 on 2026-01-06 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_transaction_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('FROZEN', 'Frozen'), ('CLOSED', 'Closed')], default='ACTIVE', max_length=15),
        ),
        migrations.AddField(
            model_name='account',
            name='kyc_status',
            field=models.CharField(choices=[('NOT_SUBMITTED', 'Not Submitted'), ('PENDING', 'Pending Verification'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='NOT_SUBMITTED', max_length=15),
        ),
    ]
